name: kapitan-dev
channels:
  - defaults
dependencies:
  - backcall
  - ca-certificates
  - dbus
  - decorator
  - expat
  - gettext
  - glib
  - icu
  - ipykernel
  - ipython_genutils
  - jpeg
  - jupyter_client
  - jupyter_core
  - libedit
  - libffi
  - libiconv
  - libpng
  - libsodium
  - ncurses
  - openssl
  - parso
  - pcre
  - pexpect
  - pip
  - prompt_toolkit
  - pygments
  - pyqt
  - python
  - pyzmq
  - qt
  - qtconsole
  - readline
  - setuptools
  - sip
  - sqlite
  - tk
  - tornado
  - traitlets
  - xz
  - zeromq
  - zlib
  - pip:
    - addict
    - allure-behave
    - allure-pytest
    - allure-python-commons
    - ansible
    - ansible-vault
    - behave
    - behave2cucumber
    - datadog
    - docker
    - ipython
    - kafka-python
    - pdpyras
    - pinject
    - pyaml
    - pytest
    - requests
    - requests-oauthlib
    - rsa
    - simplejson
    - six
    - xlsxwriter
    - xlwt
    - xmltodict
    - yamllint
    - yq
    - zipp
    - az-cli

