parameters:
  resources:
    data:
      resource_group: aop-cdt
      image: "ibm-redhat-7-6-minimal-amd64-1"
      ssh_keys:
        - "mbo200-sshkey"
        - "ach528-ssh-key"
        - "andreb-sshkey"
        - "opscadmin-sshkey"
        - "abl048-sshkey"
        - "ddt010-sshkey"
        - "eho057-sshkey"
        - "tch166-sshkey"
